---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Enable container features
      replace:
        path: /boot/cmdline.txt
        regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
        replace: '\1 {{ item }}'
      with_items:
      - "cgroup_enable=cpuset"
      - "cgroup_memory=1"
      - "cgroup_enable=memory"
      register: enabled
    - name: Reboot the box if container features enabled
      reboot:
        msg: "Reboot initiated by Ansible for enabling container features"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: enabled.changed