---
- hosts: "*"
  tasks:
    - name: "Run k3s-killall.sh"
      become: yes
      command: k3s-killall.sh
    - name: "Run k3s-uninstall.sh"
      become: yes
      command:
        cmd: k3s-uninstall.sh
        removes: /usr/local/bin/k3s-uninstall.sh
    - name: "Run k3s-agent-uninstall.sh"
      become: yes
      command:
        cmd: k3s-agent-uninstall.sh
        removes: /usr/local/bin/k3s-agent-uninstall.sh